"$schema" = "https://starship.rs/config-schema.json"

palette = "catppuccin_mocha"

format = """
[](green)\
[󰮯 󰊠 ](bg:green fg:crust)\
[](bg:teal fg:green)\
$directory\
[](bg:sky fg:teal)\
$git_branch\
$git_status\
[](bg:sapphire fg:sky)\
$c\
$rust\
$nodejs\
$bun\
$php\
$java\
$python\
[](bg:blue fg:sapphire)\
$docker_context\
[](bg:lavender fg:blue)\
$cmd_duration\
[ ](fg:lavender)
$line_break$character"""

[directory]
style = "bg:teal fg:crust"
format = "[ $path ]($style)"
home_symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Systems" = "󰲋 "
"Videos" = " "

[git_branch]
symbol = ""
style = "bg:sky"
format = '[[ $symbol $branch ](bg:sky fg:crust)]($style)'

[git_status]
style = "bg:sky"
format = '[[($all_status$ahead_behind )](bg:sky fg:crust)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[bun]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:sapphire fg:crust)]($style)'

[docker_context]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](bg:blue fg:crust)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[[󰄛](pink) ❯](bold fg:pink)'
error_symbol = '[[󰄛](maroon) ❯](bold fg:maroon)'
vimcmd_symbol = '[󰄛 ❮](bold fg:pink)'
vimcmd_replace_one_symbol = '[󰄛 ❮](bold fg:mauve)'
vimcmd_replace_symbol = '[󰄛 ❮](bold fg:mauve)'
vimcmd_visual_symbol = '[󰄛 ❮](bold fg:yellow)'

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[ $duration]($style)"
style = "bold bg:lavender fg:crust"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
